"""create users and tickets tables

Revision ID: 3138e5ac4037
Revises: 
Create Date: 2026-09-21 12:06:26.596589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3138e5ac4037'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('agent', 'admin', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.String(length=9), nullable=False),
    sa.Column('customer', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='priority'), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'closed', name='status'), nullable=False),
    sa.Column('hours', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('assigned_agent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("ticket_id ~ '^[0-9]{9}$'", name='ck_tickets_ticket_id_format'),
    sa.CheckConstraint('(hours * 2) = TRUNC(hours * 2)', name='ck_tickets_hours_step'),
    sa.CheckConstraint('hours >= 0.5 AND hours <= 40', name='ck_tickets_hours_range'),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_ticket_id'), 'tickets', ['ticket_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_ticket_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
    # Alembic's autogenerate drops the tables above but leaves the native
    # Postgres enum types behind (they're not owned by any one table), so a
    # downgrade followed by another upgrade would fail on "type already
    # exists" without dropping them explicitly here.
    sa.Enum(name='priority').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='role').drop(op.get_bind(), checkfirst=True)
